"""
Check definitions for the manuscript number-verification harness.
=================================================================

Each dict in CHECKS pins ONE numeric sentence in the manuscript to the frozen
result artifact it must come from.  `verify.py` runs them.

Schema
------
id            : short unique label for this check
claim_id      : matching row in results/final_research_audit/FINAL_MANUSCRIPT_CLAIM_REGISTRY.csv
section       : where the number appears in the manuscript
statement     : the manuscript sentence being verified (human readable)
source        : repo-relative path to the artifact (str) or [primary, ...] list
kind          : one of  band | all_in_range | scalar | per_key_scalar | count |
                        bool_all | sign_all | topk_set
filter        : {column: value | [values]}  applied before extraction (optional)
tol           : numeric tolerance (default 0.01)
abs_value     : take abs() of extracted values before comparing (optional)

kind-specific keys
------------------
band            : column, expected={low, high}      -> min≈low and max≈high
all_in_range    : column, expected={low, high}      -> every value in [low, high]
scalar          : column, expected=<number>         -> one distinct value ≈ expected
per_key_scalar  : key_column, column, expected={key: value, ...}
count           : expected=<int>, of=<int?>, where_true=<bool col?> / where_false=<bool col?>
bool_all        : column, expected=<bool>
sign_all        : column, expected="neg" | "pos"
topk_set        : group_column, sort_column, label_column, k, expected=[labels...]

Adding a check: copy the closest example below, point it at the artifact,
paste the number your manuscript prints. If it FAILs, one of the two is wrong.
"""

MODELS = ["logistic", "random_forest", "xgboost", "lightgbm", "mlp"]

CHECKS = [

    # ===================================================================== #
    # Cohort  (§3.1, §2.4, Table 1)
    # ===================================================================== #
    {
        "id": "COHORT-N",
        "claim_id": "-",
        "section": "§3.1 / abstract",
        "statement": "primary cohort N = 7,153; 666 positive; 9.31% prevalence",
        "source": "results/tables/phase2_outcome_prevalence.csv",
        "filter": {"category": "OVERALL"},
        "kind": "per_key_scalar",
        "key_column": "group_label",
        "column": "n",
        "expected": {"Primary cohort (all)": 7153},
        "tol": 0,
    },
    {
        "id": "COHORT-POS",
        "claim_id": "-",
        "section": "§3.1",
        "statement": "666 significant-fibrosis cases in the primary cohort",
        "source": "results/tables/phase2_outcome_prevalence.csv",
        "filter": {"category": "OVERALL"},
        "kind": "scalar",
        "column": "n_positive",
        "expected": 666,
        "tol": 0,
    },
    {
        "id": "COHORT-PREV",
        "claim_id": "-",
        "section": "§3.1 / abstract",
        "statement": "prevalence of significant fibrosis 9.31%",
        "source": "results/tables/phase2_outcome_prevalence.csv",
        "filter": {"category": "OVERALL"},
        "kind": "scalar",
        "column": "prevalence_pct",
        "expected": 9.31,
        "tol": 0.02,
    },

    # ===================================================================== #
    # Discrimination  (§3.2, Table 2)
    # ===================================================================== #
    {
        "id": "DISC-01-BAND",
        "claim_id": "DISC-01",
        "section": "§3.2 / abstract",
        "statement": "test AUROC 0.823–0.843 across five model families",
        "source": "results/tables/phase3_final_baseline_results.csv",
        "kind": "band",
        "column": "test_roc_auc",
        "expected": {"low": 0.8229, "high": 0.8429},
        "tol": 0.001,
    },
    {
        "id": "DISC-01-PERMODEL",
        "claim_id": "DISC-01",
        "section": "§3.2",
        "statement": "AUROC: logistic .833, RF .834, XGB .843, LGBM .839, MLP .823",
        "source": "results/tables/phase3_final_baseline_results.csv",
        "kind": "per_key_scalar",
        "key_column": "model_name",
        "column": "test_roc_auc",
        "expected": {"logistic": 0.8334, "random_forest": 0.8343, "xgboost": 0.8429,
                     "lightgbm": 0.8394, "mlp": 0.8229},
        "tol": 0.001,
    },
    {
        "id": "DISC-01-PRAUC",
        "claim_id": "DISC-01",
        "section": "§3.2 / abstract",
        "statement": "PR-AUC 0.35–0.37 at 9.31% prevalence",
        "source": "results/tables/phase3_final_baseline_results.csv",
        "kind": "band",
        "column": "test_pr_auc",
        "expected": {"low": 0.3508, "high": 0.3729},
        "tol": 0.003,
    },
    {
        "id": "DISC-02-FDR",
        "claim_id": "DISC-02",
        "section": "§3.2 / abstract",
        "statement": "0 of 10 pairwise AUROC comparisons significant after BH-FDR",
        "source": "results/tables/phase3_model_comparison_fdr.csv",
        "kind": "count",
        "where_true": "significant_after_fdr_0.05",
        "expected": 0,
        "of": 10,
    },

    # ===================================================================== #
    # Calibration  (§3.3, Table 2)
    # ===================================================================== #
    {
        "id": "CAL-OOF-INTERCEPT",
        "claim_id": "CAL-01",
        "section": "§3.3",
        "statement": "OOF calibration intercepts -2.24 to -1.86 for the 4 class-balanced models",
        "source": "results/calibration/primary_metrics_by_model.csv",
        "filter": {"model": ["logistic", "random_forest", "xgboost", "lightgbm"]},
        "kind": "all_in_range",
        "column": "calibration_intercept",
        "expected": {"low": -2.26, "high": -1.86},
        "tol": 0.01,
    },
    {
        "id": "CAL-OOF-MLP",
        "claim_id": "CAL-01",
        "section": "§3.3",
        "statement": "unweighted perceptron OOF intercept -0.28",
        "source": "results/calibration/primary_metrics_by_model.csv",
        "filter": {"model": "mlp"},
        "kind": "scalar",
        "column": "calibration_intercept",
        "expected": -0.281,
        "tol": 0.01,
    },
    {
        "id": "CAL-TEST-ECE-RAW",
        "claim_id": "CAL-01",
        "section": "§3.3 / abstract",
        "statement": "raw test ECE 0.24–0.30 (class-balanced models)",
        "source": "results/calibration/test_set_calibration_final.csv",
        "filter": {"variant": "raw",
                   "model": ["logistic", "random_forest", "xgboost", "lightgbm"]},
        "kind": "all_in_range",
        "column": "ece",
        "expected": {"low": 0.24, "high": 0.30},
        "tol": 0.005,
    },
    {
        "id": "CAL-TEST-ECE-RECAL",
        "claim_id": "CAL-01",
        "section": "§3.3 / abstract",
        "statement": "recalibrated test ECE 0.011–0.026",
        "source": "results/calibration/test_set_calibration_final.csv",
        "filter": {"variant": "recalibrated"},
        "kind": "band",
        "column": "ece",
        "expected": {"low": 0.0113, "high": 0.0264},
        "tol": 0.002,
    },
    {
        "id": "CAL-TEST-INTERCEPT-RECAL",
        "claim_id": "CAL-01",
        "section": "§3.3",
        "statement": "recalibrated test intercepts -0.15 to +0.14",
        "source": "results/calibration/test_set_calibration_final.csv",
        "filter": {"variant": "recalibrated"},
        "kind": "band",
        "column": "calibration_intercept",
        "expected": {"low": -0.154, "high": 0.142},
        "tol": 0.01,
    },

    # ===================================================================== #
    # Body-mass fairness  (§3.4, Figure 3)
    # ===================================================================== #
    {
        "id": "FAIR-BMI-01-BAND",
        "claim_id": "FAIR-BMI-01",
        "section": "§3.4 / abstract",
        "statement": "Normal-vs-Obese sensitivity gap 27–48 pp in all 5 models",
        "source": "results/fairness/fairness_inference.csv",
        "filter": {"dimension": "bmi", "category": "Obese"},
        "kind": "band",
        "column": "absolute_disparity_pp",
        "abs_value": True,
        "expected": {"low": 27.08, "high": 47.66},
        "tol": 0.2,
    },
    {
        "id": "FAIR-BMI-01-Q",
        "claim_id": "FAIR-BMI-01",
        "section": "§3.4",
        "statement": "all five BMI-Obese disparities BH q <= 0.006",
        "source": "results/fairness/fairness_inference.csv",
        "filter": {"dimension": "bmi", "category": "Obese"},
        "kind": "all_in_range",
        "column": "bh_fdr_adjusted_p",
        "expected": {"low": 0.0, "high": 0.006},
        "tol": 0.0005,
    },
    {
        "id": "FAIR-BMI-01-SIG",
        "claim_id": "FAIR-BMI-01",
        "section": "§3.4",
        "statement": "BMI-Obese sensitivity disparity BH-significant in 5/5 models",
        "source": "results/fairness/fairness_inference.csv",
        "filter": {"dimension": "bmi", "category": "Obese"},
        "kind": "count",
        "where_true": "significant_after_fdr_0.05",
        "expected": 5,
        "of": 5,
    },
    {
        "id": "FAIR-BMI-04-SHORTCUT",
        "claim_id": "FAIR-BMI-04",
        "section": "§3.4 / abstract",
        "statement": "matched-stiffness obese probability +0.19–0.33 higher, p<0.001 all 5",
        "source": "results/prepublication_fixes/fix2_bmi_shortcut_check.csv",
        "kind": "band",
        "column": "beta_is_obese",
        "expected": {"low": 0.1906, "high": 0.3319},
        "tol": 0.005,
    },
    {
        "id": "FAIR-BMI-04-P",
        "claim_id": "FAIR-BMI-04",
        "section": "§3.4",
        "statement": "matched-stiffness OLS obese coefficient p < 0.001 in all 5 models",
        "source": "results/prepublication_fixes/fix2_bmi_shortcut_check.csv",
        "kind": "all_in_range",
        "column": "p_value",
        "expected": {"low": 0.0, "high": 0.001},
        "tol": 0.0,
    },

    # ===================================================================== #
    # Age  (§3.8) -- secondary observation
    # ===================================================================== #
    {
        "id": "FAIR-AGE-01-BAND",
        "claim_id": "FAIR-AGE-01",
        "section": "§3.8",
        "statement": "Age-60+ sensitivity deficit -8.6 to -14.7 pp",
        "source": "results/fairness/fairness_inference.csv",
        "filter": {"dimension": "age", "category": "60+"},
        "kind": "band",
        "column": "absolute_disparity_pp",
        "abs_value": True,
        "expected": {"low": 8.55, "high": 14.67},
        "tol": 0.15,
    },
    {
        "id": "FAIR-AGE-01-DIR",
        "claim_id": "FAIR-AGE-01",
        "section": "§3.8",
        "statement": "Age-60+ sensitivity deficit negative in all five models",
        "source": "results/fairness/fairness_inference.csv",
        "filter": {"dimension": "age", "category": "60+"},
        "kind": "sign_all",
        "column": "absolute_disparity_pp",
        "expected": "neg",
    },
    {
        "id": "FAIR-AGE-01-SIG",
        "claim_id": "FAIR-AGE-01",
        "section": "§3.8 / abstract",
        "statement": "Age-60+ sensitivity deficit BH-significant in 4/5 models (not logistic)",
        "source": "results/fairness/fairness_inference.csv",
        "filter": {"dimension": "age", "category": "60+"},
        "kind": "count",
        "where_true": "significant_after_fdr_0.05",
        "expected": 4,
        "of": 5,
    },

    # ===================================================================== #
    # Conformal coverage  (§3.5, Table 3)
    # ===================================================================== #
    {
        "id": "CONF-01-MARGINAL",
        "claim_id": "CONF-01",
        "section": "§3.5 / abstract",
        "statement": "marginal conformal coverage 88.1–90.8%",
        "source": "results/uncertainty/marginal_coverage_test_set.csv",
        "kind": "band",
        "column": "empirical_coverage",
        "expected": {"low": 0.8812, "high": 0.9082},
        "tol": 0.002,
    },
    {
        "id": "CONF-02-BMI-OBESE",
        "claim_id": "CONF-02",
        "section": "§3.5 / abstract",
        "statement": "BMI-Obese conformal coverage 76.8–82.3%",
        "source": "results/uncertainty/subgroup_coverage.csv",
        "filter": {"dimension": "bmi", "category": "Obese"},
        "kind": "band",
        "column": "empirical_coverage",
        "expected": {"low": 0.7678, "high": 0.8233},
        "tol": 0.003,
    },
    {
        "id": "CONF-02-BMI-OBESE-SIG",
        "claim_id": "CONF-02",
        "section": "§3.5",
        "statement": "BMI-Obese under-coverage: CI excludes 0.90 for all 5 models",
        "source": "results/uncertainty/subgroup_coverage.csv",
        "filter": {"dimension": "bmi", "category": "Obese"},
        "kind": "bool_all",
        "column": "ci_excludes_target",
        "expected": True,
    },
    {
        "id": "CONF-02-AGE-60",
        "claim_id": "CONF-02",
        "section": "§3.5 / abstract",
        "statement": "Age-60+ conformal coverage 81.1–85.6%",
        "source": "results/uncertainty/subgroup_coverage.csv",
        "filter": {"dimension": "age", "category": "60+"},
        "kind": "band",
        "column": "empirical_coverage",
        "expected": {"low": 0.8111, "high": 0.8556},
        "tol": 0.003,
    },
    {
        "id": "CONF-02-AGE-60-SIG",
        "claim_id": "CONF-02",
        "section": "§3.5",
        "statement": "Age-60+ under-coverage BH-significant in 5/5 models (CAND_1)",
        "source": "results/uncertainty/subgroup_coverage.csv",
        "filter": {"dimension": "age", "category": "60+"},
        "kind": "count",
        "where_true": "significant_after_fdr_0.05",
        "expected": 5,
        "of": 5,
    },
    {
        "id": "CONF-02-OVERCOVER",
        "claim_id": "CONF-02",
        "section": "§3.5",
        "statement": "Normal-BMI and Overweight over-cover (all >= 0.94)",
        "source": "results/uncertainty/subgroup_coverage.csv",
        "filter": {"dimension": "bmi", "category": ["Normal", "Overweight"]},
        "kind": "all_in_range",
        "column": "empirical_coverage",
        "expected": {"low": 0.94, "high": 1.0},
        "tol": 0.005,
    },
    {
        "id": "CONF-03-INTERSECTION",
        "claim_id": "CONF-03",
        "section": "§3.5 / abstract",
        "statement": "Obese-and-60+ intersection (N=294) coverage 65–75%",
        "source": "results/uncertainty/intersectional_coverage_ci.csv",
        "filter": {"stage": "baseline"},
        "kind": "band",
        "column": "coverage",
        "expected": {"low": 0.6497, "high": 0.7517},
        "tol": 0.005,
    },
    {
        "id": "CONF-03-N",
        "claim_id": "CONF-03",
        "section": "§3.5 / §5",
        "statement": "intersectional cell N = 294 (not 62% of the cohort)",
        "source": "results/uncertainty/intersectional_coverage_ci.csv",
        "filter": {"stage": "baseline"},
        "kind": "scalar",
        "column": "n",
        "expected": 294,
        "tol": 0,
    },

    # ===================================================================== #
    # Demographic holdout  (§3.9)  -- pins the value the desktop PDF got wrong
    # ===================================================================== #
    {
        "id": "GEN-01-AUROC",
        "claim_id": "GEN-01",
        "section": "§3.9",
        "statement": "NHB holdout AUROC 0.772–0.789",
        "source": "results/validation/phase8_generalization_results.csv",
        "kind": "band",
        "column": "roc_auc",
        "expected": {"low": 0.7719, "high": 0.7893},
        "tol": 0.002,
    },
    {
        "id": "GEN-01-INTERCEPT",
        "claim_id": "GEN-01",
        "section": "§3.9  [PDF §IV-G was wrong here]",
        "statement": "NHB holdout calibration intercepts -0.58 to -2.17 (RAW, no recalibration)",
        "source": "results/validation/phase8_generalization_results.csv",
        "kind": "band",
        "column": "calibration_intercept",
        "expected": {"low": -2.169, "high": -0.577},
        "tol": 0.01,
    },
    {
        "id": "GEN-01-SLOPE",
        "claim_id": "GEN-01",
        "section": "§3.9",
        "statement": "NHB holdout calibration slopes 0.64–0.97",
        "source": "results/validation/phase8_generalization_results.csv",
        "kind": "band",
        "column": "calibration_slope",
        "expected": {"low": 0.636, "high": 0.972},
        "tol": 0.01,
    },

    # ===================================================================== #
    # Sensitivity / secondary outcomes  (§3.10)
    # ===================================================================== #
    {
        "id": "SECOUT-01-9p7",
        "claim_id": "SECOUT-01",
        "section": "§3.10",
        "statement": "advanced fibrosis >=9.7 kPa: AUROC 0.85–0.86",
        "source": "results/sensitivity/secondary_severity_outcomes_results.csv",
        "filter": {"outcome": "advanced_9.7kPa"},
        "kind": "all_in_range",
        "column": "roc_auc",
        "expected": {"low": 0.845, "high": 0.862},
        "tol": 0.003,
    },
    {
        "id": "SECOUT-01-13p6",
        "claim_id": "SECOUT-01",
        "section": "§3.10",
        "statement": "cirrhosis >=13.6 kPa: AUROC 0.84–0.86",
        "source": "results/sensitivity/secondary_severity_outcomes_results.csv",
        "filter": {"outcome": "cirrhosis_13.6kPa"},
        "kind": "all_in_range",
        "column": "roc_auc",
        "expected": {"low": 0.840, "high": 0.862},
        "tol": 0.003,
    },
    {
        "id": "SECOUT-01-RELABEL-ONLY",
        "claim_id": "SECOUT-01",
        "section": "§2.9  [resolves PDF §IV-H 'was it executed?' hedge]",
        "statement": "severity outcomes were RELABEL-ONLY: no retrain, no Platt refit, "
                     "no conformal repeat, test set not re-accessed for fitting (Amendment #15)",
        "source": "results/sensitivity/secondary_severity_outcomes_results.csv",
        "kind": "bool_all",
        "column": "retrained",
        "expected": False,
    },
    {
        "id": "SECOUT-01-NO-REFIT",
        "claim_id": "SECOUT-01",
        "section": "§2.9",
        "statement": "severity outcomes: Platt parameters not re-fit",
        "source": "results/sensitivity/secondary_severity_outcomes_results.csv",
        "kind": "bool_all",
        "column": "platt_refit",
        "expected": False,
    },
    {
        "id": "SECOUT-01-NO-TESTACCESS",
        "claim_id": "SECOUT-01",
        "section": "§2.9",
        "statement": "severity outcomes: locked test not re-accessed for model fitting",
        "source": "results/sensitivity/secondary_severity_outcomes_results.csv",
        "kind": "bool_all",
        "column": "test_set_reaccessed_for_model_fitting",
        "expected": False,
    },

    # ===================================================================== #
    # Training-time mitigation  (§3.7b, Table 4)  -- Amendment #19
    # ===================================================================== #
    {
        "id": "MIT-07-VERDICT",
        "claim_id": "MIT-07",
        "section": "§3.7b / abstract",
        "statement": "training-time reweighting verdict: NEGATIVE (no efficacy), both arms",
        "source": "results/training_time_mitigation/decision.csv",
        "kind": "per_key_scalar",
        "key_column": "arm",
        "column": "verdict",
        "expected": {},   # placeholder; string verdicts checked via MIT-07-VERDICT-STR
        "tol": 0,
        "skip": True,
    },
    {
        "id": "MIT-07-BMI-GAP-REDUCED",
        "claim_id": "MIT-07",
        "section": "§3.7b",
        "statement": "after reweighting, Normal-vs-Obese gap +14 to +17 pp (Arm A, 4 families)",
        "source": "results/training_time_mitigation/test_subgroup_sensitivity.csv",
        "filter": {"arm": "A", "dimension": "bmi", "category": "Obese"},
        "kind": "band",
        "column": "disparity_pp",
        "expected": {"low": 14.0, "high": 17.5},
        "tol": 1.0,
    },
    {
        "id": "MIT-07-BMI-GAP-NS",
        "claim_id": "MIT-07",
        "section": "§3.7b",
        "statement": "after reweighting, BMI-Obese gap no longer BH-significant (Arm A)",
        "source": "results/training_time_mitigation/test_subgroup_sensitivity.csv",
        "filter": {"arm": "A", "dimension": "bmi", "category": "Obese"},
        "kind": "count",
        "where_true": "significant_after_fdr_0.05",
        "expected": 0,
    },
    {
        "id": "MIT-07-NEW-SEX-DISPARITY",
        "claim_id": "MIT-07",
        "section": "§3.7b / DO_NOT_CLAIM 9d",
        "statement": "reweighting created a new BH-significant logistic Female sensitivity disparity",
        "source": "results/training_time_mitigation/test_subgroup_sensitivity.csv",
        "filter": {"arm": "A", "model": "logistic", "dimension": "sex", "category": "Female"},
        "kind": "scalar",
        "column": "disparity_pp",
        "expected": -15.09,
        "tol": 0.2,
    },

    # ===================================================================== #
    # Interpretability  (§3.11)
    # ===================================================================== #
    # --- §3.11 rewritten 2026 to match the artifacts exactly; these checks
    #     verify the corrected sentence, component by component. ---
    {
        "id": "INT-01-BMI-TOP1",
        "claim_id": "INT-01",
        "section": "§3.11",
        "statement": "BMI ranks first by permutation importance in every model family",
        "source": "results/tables/interpretability_permutation_importance.csv",
        "kind": "topk_set",
        "group_column": "model",
        "sort_column": "importance_mean_auc_drop",
        "label_column": "predictor",
        "k": 1,
        "expected": ["BMXBMI"],
    },
    {
        "id": "INT-01-BMI-COEF-TOP1",
        "claim_id": "INT-01",
        "section": "§3.11",
        "statement": "BMI has the largest standardised logistic-regression coefficient",
        "source": "results/tables/interpretability_logistic_coefficients.csv",
        "kind": "topk_set",
        # no group_column -> whole file is one ranking
        "sort_column": "standardized_coefficient",
        "label_column": "predictor",
        "k": 1,
        "abs_value_sort": True,
        "expected": ["BMXBMI"],
    },
    {
        "id": "INT-01-TOP4-BOOSTING",
        "claim_id": "INT-01",
        "section": "§3.11",
        "statement": "top four for XGBoost and LightGBM = {BMI, age, ALT, AST} (perm. importance)",
        "source": "results/tables/interpretability_permutation_importance.csv",
        "filter": {"model": ["xgboost", "lightgbm"]},
        "kind": "topk_set",
        "group_column": "model",
        "sort_column": "importance_mean_auc_drop",
        "label_column": "predictor",
        "k": 4,
        "expected": ["RIDAGEYR", "BMXBMI", "LBXSATSI", "LBXSASSI"],
    },
    {
        "id": "INT-01-RF-HDL",
        "claim_id": "INT-01",
        "section": "§3.11",
        "statement": "for random forest, HDL is in the top four and AST is not (perm. importance)",
        "source": "results/tables/interpretability_permutation_importance.csv",
        "filter": {"model": "random_forest"},
        "kind": "topk_set",
        "group_column": "model",
        "sort_column": "importance_mean_auc_drop",
        "label_column": "predictor",
        "k": 4,
        "expected": ["RIDAGEYR", "BMXBMI", "LBXSATSI", "LBDHDD"],
    },

    # ===================================================================== #
    # FIB-4 clinical baseline  (\S3.9b / \S4)  -- post-freeze addendum, added
    # 2026-09-14 after the twentieth protocol amendment closed; see
    # documentation/clinical_baselines/FIB4_BASELINE_REPORT.md
    # ===================================================================== #
    {
        "id": "FIB4-01-AUROC",
        "claim_id": "-",
        "section": "\\S3.9b",
        "statement": "FIB-4 discrimination AUROC 0.638, 95% CI 0.597-0.680",
        "source": "results/clinical_baselines/fib4_discrimination.csv",
        "kind": "scalar",
        "column": "roc_auc",
        "expected": 0.6379,
        "tol": 0.001,
    },
    {
        "id": "FIB4-01-CI-LOW",
        "claim_id": "-",
        "section": "\\S3.9b",
        "statement": "FIB-4 AUROC 95% CI lower bound 0.597",
        "source": "results/clinical_baselines/fib4_discrimination.csv",
        "kind": "scalar",
        "column": "roc_auc_95ci_low",
        "expected": 0.5971,
        "tol": 0.001,
    },
    {
        "id": "FIB4-01-CI-HIGH",
        "claim_id": "-",
        "section": "\\S3.9b",
        "statement": "FIB-4 AUROC 95% CI upper bound 0.680",
        "source": "results/clinical_baselines/fib4_discrimination.csv",
        "kind": "scalar",
        "column": "roc_auc_95ci_high",
        "expected": 0.6795,
        "tol": 0.001,
    },
    {
        "id": "FIB4-02-BMI-DISPARITY",
        "claim_id": "-",
        "section": "\\S3.9b",
        "statement": "FIB-4 under-detects Obese vs. Normal-BMI by 25.1 pp (q=0.027), opposite the five learned models",
        "source": "results/clinical_baselines/fib4_fairness_inference.csv",
        "filter": {"dimension": "bmi", "category": "Obese"},
        "kind": "scalar",
        "column": "absolute_disparity_pp",
        "abs_value": True,
        "expected": 25.1299,
        "tol": 0.02,
    },
    {
        "id": "FIB4-02-BMI-Q",
        "claim_id": "-",
        "section": "\\S3.9b",
        "statement": "FIB-4 BMI-Obese disparity BH q = 0.027",
        "source": "results/clinical_baselines/fib4_fairness_inference.csv",
        "filter": {"dimension": "bmi", "category": "Obese"},
        "kind": "scalar",
        "column": "bh_fdr_adjusted_p",
        "expected": 0.027,
        "tol": 0.001,
    },
    {
        "id": "FIB4-03-AGE-DISPARITY",
        "claim_id": "-",
        "section": "\\S3.9b",
        "statement": "FIB-4 over-detects Age 60+ vs. 40-59 by +33.2 pp",
        "source": "results/clinical_baselines/fib4_fairness_inference.csv",
        "filter": {"dimension": "age", "category": "60+"},
        "kind": "scalar",
        "column": "absolute_disparity_pp",
        "expected": 33.1683,
        "tol": 0.02,
    },
    {
        "id": "FIB4-04-COVERAGE-OBESE",
        "claim_id": "-",
        "section": "\\S3.9b",
        "statement": "FIB-4 conformal coverage, Obese: 84.1% (Wilson CI excludes 90%)",
        "source": "results/clinical_baselines/fib4_subgroup_coverage.csv",
        "filter": {"dimension": "bmi", "category": "Obese"},
        "kind": "scalar",
        "column": "empirical_coverage",
        "expected": 0.84145,
        "tol": 0.001,
    },
    {
        "id": "FIB4-04-COVERAGE-NORMAL",
        "claim_id": "-",
        "section": "\\S3.9b",
        "statement": "FIB-4 conformal coverage, Normal-BMI: 93.8% (Wilson CI excludes 90%)",
        "source": "results/clinical_baselines/fib4_subgroup_coverage.csv",
        "filter": {"dimension": "bmi", "category": "Normal"},
        "kind": "scalar",
        "column": "empirical_coverage",
        "expected": 0.937722,
        "tol": 0.001,
    },
    {
        "id": "FIB4-04-COVERAGE-AGE60",
        "claim_id": "-",
        "section": "\\S3.9b",
        "statement": "FIB-4 conformal coverage, Age 60+: 83.8% (Wilson CI excludes 90%)",
        "source": "results/clinical_baselines/fib4_subgroup_coverage.csv",
        "filter": {"dimension": "age", "category": "60+"},
        "kind": "scalar",
        "column": "empirical_coverage",
        "expected": 0.838057,
        "tol": 0.001,
    },
    {
        "id": "FIB4-05-MATCHED-STIFFNESS-RAW",
        "claim_id": "-",
        "section": "\\S3.9b",
        "statement": "FIB-4 matched-stiffness obese coefficient, native score scale: beta=-0.776, p<0.001",
        "source": "results/clinical_baselines/fib4_matched_stiffness.csv",
        "filter": {"dependent_variable": "fib4_raw_score"},
        "kind": "scalar",
        "column": "beta_is_obese",
        "expected": -0.7755,
        "tol": 0.001,
    },
    {
        "id": "FIB4-05-MATCHED-STIFFNESS-PROB",
        "claim_id": "-",
        "section": "\\S3.9b",
        "statement": "FIB-4 matched-stiffness obese coefficient, auxiliary-probability scale (same units as the five learned models' 0.19-0.33 shortcut): beta=-0.073, p<0.001",
        "source": "results/clinical_baselines/fib4_matched_stiffness.csv",
        "filter": {"dependent_variable": "auxiliary_probability"},
        "kind": "scalar",
        "column": "beta_is_obese",
        "expected": -0.0734,
        "tol": 0.001,
    },

    # ===================================================================== #
    # Survey-weighted sensitivity check  (Limitations)  -- post-freeze
    # addendum, added 2026-09-14; see
    # documentation/sensitivity/SURVEY_WEIGHTED_REPORT.md
    # ===================================================================== #
    {
        "id": "SVY-01-PREVALENCE",
        "claim_id": "-",
        "section": "\\S5 (Limitations)",
        "statement": "survey-weighted prevalence 8.30% (unweighted 9.31%)",
        "source": "results/sensitivity/survey_weighted/svy_prevalence_summary.csv",
        "kind": "scalar",
        "column": "weighted_prevalence_pct",
        "expected": 8.2954,
        "tol": 0.01,
    },
    {
        "id": "SVY-01-CI-LOW",
        "claim_id": "-",
        "section": "\\S5 (Limitations)",
        "statement": "survey-weighted prevalence 95% CI lower bound 7.00%",
        "source": "results/sensitivity/survey_weighted/svy_prevalence_summary.csv",
        "kind": "scalar",
        "column": "weighted_95ci_low_pct",
        "expected": 6.9981,
        "tol": 0.01,
    },
    {
        "id": "SVY-01-CI-HIGH",
        "claim_id": "-",
        "section": "\\S5 (Limitations)",
        "statement": "survey-weighted prevalence 95% CI upper bound 9.81%",
        "source": "results/sensitivity/survey_weighted/svy_prevalence_summary.csv",
        "kind": "scalar",
        "column": "weighted_95ci_high_pct",
        "expected": 9.8078,
        "tol": 0.01,
    },
    {
        "id": "SVY-02-UNWEIGHTED-GAP",
        "claim_id": "-",
        "section": "\\S5 (Limitations)",
        "statement": "unweighted BMI-Obese-vs-Normal gap 27.1-47.7 pp (input to the 43-65% attenuation claim)",
        "source": "results/sensitivity/survey_weighted/svy_bmi_sensitivity_gap_summary.csv",
        "kind": "band",
        "column": "unweighted_gap_obese_minus_normal_pp",
        "expected": {"low": 27.0779, "high": 47.6623},
        "tol": 0.01,
    },
    {
        "id": "SVY-02-WEIGHTED-GAP",
        "claim_id": "-",
        "section": "\\S5 (Limitations)",
        "statement": "survey-weighted BMI-Obese-vs-Normal gap 9.5-22.1 pp; preserves direction in 5/5, attenuated 43-65% vs. the unweighted gap above, with overlapping subgroup CIs",
        "source": "results/sensitivity/survey_weighted/svy_bmi_sensitivity_gap_summary.csv",
        "kind": "band",
        "column": "weighted_gap_obese_minus_normal_pp",
        "expected": {"low": 9.5043, "high": 22.1339},
        "tol": 0.01,
    },

    # ===================================================================== #
    # Temporal validation, NHANES 2021-2023 (\\S3.10 / \\S4.8) -- post-freeze
    # tier, added after the twentieth protocol amendment closed; see
    # temporal_validation_2021_2023/documentation/. Pins the headline numbers
    # of the Temporal Validation subsection, which the automated registry did
    # not previously cover.
    # ===================================================================== #
    {
        "id": "TEMP-COHORT-N",
        "claim_id": "-",
        "section": "\\S3.10",
        "statement": "temporal cohort N = 4,910",
        "source": "temporal_validation_2021_2023/results/temporal_discrimination_calibration_results.csv",
        "kind": "scalar",
        "column": "n",
        "expected": 4910,
        "tol": 0,
    },
    {
        "id": "TEMP-COHORT-PREV",
        "claim_id": "-",
        "section": "\\S3.10",
        "statement": "temporal cohort prevalence 11.5% (vs. 9.3% development)",
        "source": "temporal_validation_2021_2023/results/temporal_outcome_drift.csv",
        "filter": {"metric": "prevalence_pct"},
        "kind": "scalar",
        "column": "value_2021_2023",
        "expected": 11.466,
        "tol": 0.01,
    },
    {
        "id": "TEMP-01-AUROC-BAND",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "temporal AUROC 0.776-0.782, applied unchanged",
        "source": "temporal_validation_2021_2023/results/temporal_discrimination_calibration_results.csv",
        "filter": {"variant": "raw"},
        "kind": "band",
        "column": "auroc",
        "expected": {"low": 0.7758, "high": 0.7819},
        "tol": 0.001,
    },
    {
        "id": "TEMP-01-DELTA-BAND",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "AUROC delta vs. development cohort: -0.04 to -0.06",
        "source": "temporal_validation_2021_2023/results/temporal_discrimination_calibration_results.csv",
        "filter": {"variant": "raw"},
        "kind": "band",
        "column": "auroc_delta",
        "expected": {"low": -0.0621, "high": -0.0416},
        "tol": 0.001,
    },
    {
        "id": "TEMP-02-ECE-RECAL",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "frozen Platt recalibration transported: ECE 0.016-0.021",
        "source": "temporal_validation_2021_2023/results/temporal_discrimination_calibration_results.csv",
        "filter": {"variant": "recalibrated"},
        "kind": "band",
        "column": "ece",
        "expected": {"low": 0.0164, "high": 0.0207},
        "tol": 0.001,
    },
    {
        "id": "TEMP-02-BRIER-RECAL",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "recalibrated Brier 0.085-0.087 (up from approx. 0.07)",
        "source": "temporal_validation_2021_2023/results/temporal_discrimination_calibration_results.csv",
        "filter": {"variant": "recalibrated"},
        "kind": "band",
        "column": "brier",
        "expected": {"low": 0.0852, "high": 0.0867},
        "tol": 0.001,
    },
    {
        "id": "TEMP-02-INTERCEPT-RECAL",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "recalibrated intercepts -0.11 to +0.22",
        "source": "temporal_validation_2021_2023/results/temporal_discrimination_calibration_results.csv",
        "filter": {"variant": "recalibrated"},
        "kind": "band",
        "column": "calib_intercept",
        "expected": {"low": -0.1054, "high": 0.2175},
        "tol": 0.001,
    },
    {
        "id": "TEMP-03-ALKPHOS-SMD",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "alkaline-phosphatase standardized mean difference 0.25 (analyzer-shift signal)",
        "source": "temporal_validation_2021_2023/results/temporal_predictor_drift.csv",
        "filter": {"predictor": "LBXSAPSI"},
        "kind": "scalar",
        "column": "standardized_mean_diff",
        "expected": 0.246,
        "tol": 0.01,
    },
    {
        "id": "TEMP-03-ALT-SMD",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "ALT standardized mean difference -0.02 (stable)",
        "source": "temporal_validation_2021_2023/results/temporal_predictor_drift.csv",
        "filter": {"predictor": "LBXSATSI"},
        "kind": "scalar",
        "column": "standardized_mean_diff",
        "expected": -0.023,
        "tol": 0.01,
    },
    {
        "id": "TEMP-04-COVARIATE-RECOVERY",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "reweighting to development covariate distribution recovers approx. 17% of the AUROC drop (13.6-21% across the 5 models)",
        "source": "temporal_validation_2021_2023/results/temporal_drop_covariate_shift.csv",
        "kind": "band",
        "column": "fraction_of_drop_recovered",
        "expected": {"low": 0.136, "high": 0.21},
        "tol": 0.01,
    },
    {
        "id": "TEMP-04-QUANTILE-MAPPING",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "quantile-mapping any single predictor recovers essentially none of the AUROC drop (all |delta AUROC| < 0.004)",
        "source": "temporal_validation_2021_2023/results/temporal_drop_predictor_attribution.csv",
        "kind": "all_in_range",
        "column": "auroc_recovery",
        "expected": {"low": -0.0036, "high": 0.0036},
        "tol": 0.0005,
    },
    {
        "id": "TEMP-05-BMI-GAP-BAND",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "temporal BMI-Obese-vs-Normal sensitivity gap 63-72 pp, all 5 models",
        "source": "temporal_validation_2021_2023/results/temporal_fairness_results.csv",
        "filter": {"dimension": "bmi", "category": "Obese"},
        "kind": "band",
        "column": "absolute_disparity_pp",
        "expected": {"low": 63.0487, "high": 71.917},
        "tol": 0.01,
    },
    {
        "id": "TEMP-05-BMI-GAP-DEV-BAND",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "development-cohort BMI-Obese-vs-Normal gap for comparison: 27-48 pp",
        "source": "temporal_validation_2021_2023/results/temporal_fairness_results.csv",
        "filter": {"dimension": "bmi", "category": "Obese"},
        "kind": "band",
        "column": "disparity_pp_2017_2020",
        "expected": {"low": 27.0779, "high": 47.6623},
        "tol": 0.01,
    },
    {
        "id": "TEMP-05-BMI-GAP-Q",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "temporal BMI-Obese-vs-Normal gap significant at q<0.001 in all 5 models",
        "source": "temporal_validation_2021_2023/results/temporal_fairness_results.csv",
        "filter": {"dimension": "bmi", "category": "Obese"},
        "kind": "all_in_range",
        "column": "bh_fdr_adjusted_p",
        "expected": {"low": 0.0, "high": 0.001},
        "tol": 0,
    },
    {
        "id": "TEMP-06-AGE60-REVERSAL-BAND",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "age-60+ sensitivity deficit reversed: 2.6-10.3 pp higher than 40-59",
        "source": "temporal_validation_2021_2023/results/temporal_fairness_results.csv",
        "filter": {"dimension": "age", "category": "60+"},
        "kind": "band",
        "column": "absolute_disparity_pp",
        "expected": {"low": 2.5632, "high": 10.3377},
        "tol": 0.01,
    },
    {
        "id": "TEMP-06-AGE60-REVERSAL-SIG",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "age-60+ reversal significant only for logistic regression (1/5)",
        "source": "temporal_validation_2021_2023/results/temporal_fairness_results.csv",
        "filter": {"dimension": "age", "category": "60+"},
        "kind": "count",
        "where_true": "significant_after_fdr_0.05",
        "expected": 1,
        "of": 5,
    },
    {
        "id": "TEMP-07-MATCHED-STIFFNESS-BAND",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "temporal matched-stiffness obese coefficient 0.21-0.40 (all p<0.001)",
        "source": "temporal_validation_2021_2023/results/temporal_matched_stiffness_shortcut.csv",
        "kind": "band",
        "column": "beta_is_obese",
        "expected": {"low": 0.2138, "high": 0.4031},
        "tol": 0.001,
    },
    {
        "id": "TEMP-07-MATCHED-STIFFNESS-DEV-BAND",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "development-cohort matched-stiffness coefficient for comparison: 0.19-0.33",
        "source": "temporal_validation_2021_2023/results/temporal_matched_stiffness_shortcut.csv",
        "kind": "band",
        "column": "beta_is_obese_2017_2020",
        "expected": {"low": 0.1906, "high": 0.3319},
        "tol": 0.001,
    },
    {
        "id": "TEMP-08-CONFORMAL-MARGINAL",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "temporal marginal conformal coverage 0.878-0.902",
        "source": "temporal_validation_2021_2023/results/temporal_conformal_results.csv",
        "filter": {"scope": "marginal"},
        "kind": "band",
        "column": "empirical_coverage",
        "expected": {"low": 0.8784, "high": 0.902},
        "tol": 0.001,
    },
    {
        "id": "TEMP-08-CONFORMAL-OBESE",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "temporal obese conformal coverage 0.76-0.81",
        "source": "temporal_validation_2021_2023/results/temporal_conformal_results.csv",
        "filter": {"scope": "bmi_Obese"},
        "kind": "band",
        "column": "empirical_coverage",
        "expected": {"low": 0.7611, "high": 0.8128},
        "tol": 0.001,
    },
    {
        "id": "TEMP-08-CONFORMAL-AGE60",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "temporal age-60+ conformal coverage 0.85-0.88",
        "source": "temporal_validation_2021_2023/results/temporal_conformal_results.csv",
        "filter": {"scope": "age_60plus"},
        "kind": "band",
        "column": "empirical_coverage",
        "expected": {"low": 0.8454, "high": 0.8758},
        "tol": 0.001,
    },
    {
        "id": "TEMP-08-CONFORMAL-INTERSECTION",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "temporal obese-cap-60+ intersection (N=788) coverage 0.69-0.75",
        "source": "temporal_validation_2021_2023/results/temporal_conformal_results.csv",
        "filter": {"scope": "Obese_x_60plus"},
        "kind": "band",
        "column": "empirical_coverage",
        "expected": {"low": 0.6865, "high": 0.7513},
        "tol": 0.001,
    },
    {
        "id": "TEMP-08-CONFORMAL-INTERSECTION-N",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "temporal obese-cap-60+ intersection N = 788",
        "source": "temporal_validation_2021_2023/results/temporal_conformal_results.csv",
        "filter": {"scope": "Obese_x_60plus"},
        "kind": "scalar",
        "column": "n",
        "expected": 788,
        "tol": 0,
    },
    {
        "id": "TEMP-09-DISSOCIATION-REPLICATED",
        "claim_id": "-",
        "section": "\\S4.8",
        "statement": "fairness-coverage dissociation reproduced in all 5 models",
        "source": "temporal_validation_2021_2023/results/temporal_dissociation.csv",
        "kind": "bool_all",
        "column": "dissociation_replicated",
        "expected": True,
    },

    # ===================================================================== #
    # Table III exact per-model cells (BMI + Age-60+), value and CI bracket
    # ===================================================================== #
    {
        "id": "TAB3-BMI-PERMODEL",
        "claim_id": "FAIR-BMI-01",
        "section": "Table III",
        "statement": "Table III BMI column point estimates: -48/-32/-31/-27/-39 pp",
        "source": "results/fairness/fairness_inference.csv",
        "filter": {"dimension": "bmi", "category": "Obese"},
        "kind": "per_key_scalar",
        "key_column": "model",
        "column": "absolute_disparity_pp",
        "abs_value": True,
        "expected": {"logistic": 47.6623, "random_forest": 31.6234, "xgboost": 31.3636,
                     "lightgbm": 27.0779, "mlp": 39.026},
        "tol": 0.05,
    },
    {
        "id": "TAB3-BMI-CI-LOW",
        "claim_id": "FAIR-BMI-01",
        "section": "Table III",
        "statement": "Table III BMI column CI lower bounds: -70/-53/-54/-49/-61 pp",
        "source": "results/fairness/fairness_inference.csv",
        "filter": {"dimension": "bmi", "category": "Obese"},
        "kind": "per_key_scalar",
        "key_column": "model",
        "column": "ci_upper_pp",
        "expected": {"logistic": 69.5017, "random_forest": 53.357, "xgboost": 53.5666,
                     "lightgbm": 48.5048, "mlp": 60.6754},
        "tol": 0.05,
    },
    {
        "id": "TAB3-BMI-CI-HIGH",
        "claim_id": "FAIR-BMI-01",
        "section": "Table III",
        "statement": "Table III BMI column CI upper bounds: -26/-10/-11/-7/-19 pp",
        "source": "results/fairness/fairness_inference.csv",
        "filter": {"dimension": "bmi", "category": "Obese"},
        "kind": "per_key_scalar",
        "key_column": "model",
        "column": "ci_lower_pp",
        "expected": {"logistic": 25.6847, "random_forest": 10.2285, "xgboost": 11.1043,
                     "lightgbm": 6.7666, "mlp": 18.6747},
        "tol": 0.05,
    },
    {
        "id": "TAB3-AGE-PERMODEL",
        "claim_id": "FAIR-AGE-01",
        "section": "Table III",
        "statement": "Table III Age 60+ column point estimates: -9/-13/-11/-14/-15 pp",
        "source": "results/fairness/fairness_inference.csv",
        "filter": {"dimension": "age", "category": "60+"},
        "kind": "per_key_scalar",
        "key_column": "model",
        "column": "absolute_disparity_pp",
        "abs_value": True,
        "expected": {"logistic": 8.5509, "random_forest": 13.1563, "xgboost": 11.2361,
                     "lightgbm": 14.1464, "mlp": 14.6715},
        "tol": 0.05,
    },
    {
        "id": "TAB3-AGE-Q-LOGISTIC",
        "claim_id": "FAIR-AGE-01",
        "section": "Table III",
        "statement": "Table III Age 60+ logistic footnote q=0.195",
        "source": "results/fairness/fairness_inference.csv",
        "filter": {"dimension": "age", "category": "60+", "model": "logistic"},
        "kind": "scalar",
        "column": "bh_fdr_adjusted_p",
        "expected": 0.195,
        "tol": 0.001,
    },

    # ===================================================================== #
    # Table IV exact per-model cells not covered by the CONF-* band checks
    # ===================================================================== #
    {
        "id": "TAB4-MARGINAL-PERMODEL",
        "claim_id": "CONF-01",
        "section": "Table IV",
        "statement": "Table IV Marg. column: 90.82/89.61/88.12/89.61/89.19",
        "source": "results/uncertainty/marginal_coverage_test_set.csv",
        "kind": "per_key_scalar",
        "key_column": "model",
        "column": "empirical_coverage",
        "expected": {"logistic": 0.908201, "random_forest": 0.896086, "xgboost": 0.881174,
                     "lightgbm": 0.896086, "mlp": 0.891892},
        "tol": 0.0005,
    },
    {
        "id": "TAB4-NORMAL-PERMODEL",
        "claim_id": "CONF-02",
        "section": "Table IV",
        "statement": "Table IV Normal column: 96.80/96.44/96.09/96.98/95.37",
        "source": "results/uncertainty/subgroup_coverage.csv",
        "filter": {"dimension": "bmi", "category": "Normal"},
        "kind": "per_key_scalar",
        "key_column": "model",
        "column": "empirical_coverage",
        "expected": {"logistic": 0.967972, "random_forest": 0.964413, "xgboost": 0.960854,
                     "lightgbm": 0.969751, "mlp": 0.953737},
        "tol": 0.0005,
    },
    {
        "id": "TAB4-OVERWEIGHT-PERMODEL",
        "claim_id": "CONF-02",
        "section": "Table IV",
        "statement": "Table IV Overwt. column: 96.88/96.29/96.29/97.18/94.80",
        "source": "results/uncertainty/subgroup_coverage.csv",
        "filter": {"dimension": "bmi", "category": "Overweight"},
        "kind": "per_key_scalar",
        "key_column": "model",
        "column": "empirical_coverage",
        "expected": {"logistic": 0.968796, "random_forest": 0.962853, "xgboost": 0.962853,
                     "lightgbm": 0.971768, "mlp": 0.947994},
        "tol": 0.0005,
    },
    {
        "id": "TAB4-4059-PERMODEL",
        "claim_id": "CONF-02",
        "section": "Table IV",
        "statement": "Table IV 40-59 column: 91.88/89.32/89.02/90.08/88.42",
        "source": "results/uncertainty/subgroup_coverage.csv",
        "filter": {"dimension": "age", "category": "40-59"},
        "kind": "per_key_scalar",
        "key_column": "model",
        "column": "empirical_coverage",
        "expected": {"logistic": 0.918797, "random_forest": 0.893233, "xgboost": 0.890226,
                     "lightgbm": 0.900752, "mlp": 0.884211},
        "tol": 0.0005,
    },
    {
        "id": "TAB4-60PLUS-PERMODEL",
        "claim_id": "CONF-02",
        "section": "Table IV",
        "statement": "Table IV 60+ column: 84.89/85.56/81.11/84.75/83.81",
        "source": "results/uncertainty/subgroup_coverage.csv",
        "filter": {"dimension": "age", "category": "60+"},
        "kind": "per_key_scalar",
        "key_column": "model",
        "column": "empirical_coverage",
        "expected": {"logistic": 0.848853, "random_forest": 0.855601, "xgboost": 0.811066,
                     "lightgbm": 0.847503, "mlp": 0.838057},
        "tol": 0.0005,
    },

    # ===================================================================== #
    # Predictor importance (§ Robustness): BMI top-1 every model,
    # age 2nd in 4, 3rd in MLP where AST is 2nd (the old C10 bug)
    # ===================================================================== #
    {
        "id": "PRED-01-AGE-RANK-BOOSTING",
        "claim_id": "INT-01",
        "section": "\\S4.9 (Robustness)",
        "statement": "age ranks 2nd predictor for random_forest/xgboost/lightgbm",
        "source": "results/tables/interpretability_permutation_importance.csv",
        "filter": {"model": ["random_forest", "xgboost", "lightgbm"], "predictor": "RIDAGEYR"},
        "kind": "all_in_range",
        "column": "importance_mean_auc_drop",
        "expected": {"low": 0.0496, "high": 0.0602},
        "tol": 0.001,
    },
    {
        "id": "PRED-01-MLP-AGE-3RD-AST-2ND",
        "claim_id": "INT-01",
        "section": "\\S4.9 (Robustness)",
        "statement": "MLP: AST (0.0472) outranks age (0.0403), i.e. age is 3rd not 2nd",
        "source": "results/tables/interpretability_permutation_importance.csv",
        "filter": {"model": "mlp", "predictor": ["LBXSASSI", "RIDAGEYR"]},
        "kind": "per_key_scalar",
        "key_column": "predictor",
        "column": "importance_mean_auc_drop",
        "expected": {"LBXSASSI": 0.047177, "RIDAGEYR": 0.04028},
        "tol": 0.0005,
    },

    # ===================================================================== #
    # Mitigation (Table V / \S4.6): training-time reweighting per-model costs
    # ===================================================================== #
    {
        "id": "MIT-08-REWEIGHT-AUROC-COST",
        "claim_id": "MIT-07",
        "section": "Table V",
        "statement": "reweighting (BMI, arm A) AUROC cost -0.02 to -0.03 across 4 models",
        "source": "results/training_time_mitigation/cost_accounting.csv",
        "filter": {"arm": "A"},
        "kind": "band",
        "column": "delta_auroc",
        "expected": {"low": -0.032714, "high": -0.021463},
        "tol": 0.001,
    },
    {
        "id": "MIT-08-REWEIGHT-SPEC-COST-RANGE",
        "claim_id": "MIT-07",
        "section": "Table V",
        "statement": ("reweighting (BMI, arm A) specificity cost per model spans -0.7 to "
                       "-12.2 pp; Table V's single '-12 pp' figure is the logistic-only "
                       "value, not representative of the 4-model range -- flagged during "
                       "the 2026-09-27 evaluation pass, not yet reworded in the prose"),
        "source": "results/training_time_mitigation/cost_accounting.csv",
        "filter": {"arm": "A"},
        "kind": "all_in_range",
        "column": "delta_spec",
        "abs_value": True,
        "expected": {"low": 0.007208, "high": 0.122326},
        "tol": 0.001,
    },
    {
        "id": "MIT-08-EO-NORMAL-SPEC-BASELINE",
        "claim_id": "-",
        "section": "\\S4.9 (Robustness) -- equal-opportunity post-processing",
        "statement": "normal-BMI baseline specificity 89-96% before equal-opportunity post-processing",
        "source": "results/diagnostics/stage1/correct_fairness_postprocessing_results.csv",
        "filter": {"scope": "BMI_Normal", "method": "recalibrated_baseline"},
        "kind": "band",
        "column": "specificity",
        "expected": {"low": 0.8889, "high": 0.9611},
        "tol": 0.001,
    },
    {
        "id": "MIT-08-EO-NORMAL-SPEC-POST",
        "claim_id": "-",
        "section": "\\S4.9 (Robustness) -- equal-opportunity post-processing",
        "statement": "normal-BMI specificity drops to 46-61% after equal-opportunity post-processing",
        "source": "results/diagnostics/stage1/correct_fairness_postprocessing_results.csv",
        "filter": {"scope": "BMI_Normal", "method": "eo_bmi_postprocessed"},
        "kind": "band",
        "column": "specificity",
        "expected": {"low": 0.463, "high": 0.6056},
        "tol": 0.001,
    },
]

# Drop entries flagged skip=True (kept in-file as templates)
CHECKS = [c for c in CHECKS if not c.get("skip")]
